/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const customermessage_Logic_Preprocessing = require('./code/customermessage-logic-preprocessing');
const customermessage_Logic_GenerateReply = require('./code/customermessage-logic-generateReply');
const customermessage_Logic_MaintainSO = require('./code/customermessage-logic-maintainSO');
const productfaq_Logic = require('./code/productfaq-logic');

class josebecerra_04_a19Srv extends LCAPApplicationService {
    async init() {

        this.before('READ', 'CustomerMessage', async (request) => {
            await customermessage_Logic_Preprocessing(request);
        });

        this.before('Action1', 'CustomerMessage', async (request) => {
            await customermessage_Logic_GenerateReply(request);
        });

        this.before('Action1', 'CustomerMessage', async (request) => {
            await customermessage_Logic_MaintainSO(request);
        });

        this.after(['CREATE', 'UPDATE'], 'ProductFAQ', async (results, request) => {
            await productfaq_Logic(results, request);
        });

        return super.init();
    }
}


module.exports = {
    josebecerra_04_a19Srv
};